/** Curated semiconductor / electronics focus set for the development subset. */

export const FOCUS_TICKERS = [
  'TSM',
  'NVDA',
  'AMD',
  'INTC',
  'MU',
  'AAPL',
  'MSFT',
  'AVGO',
  'QCOM',
  'AMAT',
  'LRCX',
  'KLAC',
  'ASML',
  'TXN',
  'ADI',
  'NXPI',
  'MRVL',
  'AMKR',
  'SNPS',
  'CDNS',
  'ON',
  'MCHP',
  'GFS',
  'TSEM',
  'ARM',
  'TER',
  'ENTG',
]

/** Apple / Microsoft only stay in the graph when the other party is electronics-related. */
export const PLATFORM_TICKERS = ['AAPL', 'MSFT']

export const COMPANY_PROFILES = [
  {
    id: 'tsmc',
    canonicalName: 'Taiwan Semiconductor Manufacturing Company',
    aliases: [
      'TSMC',
      'Taiwan Semiconductor',
      'Taiwan Semiconductor Manufacturing',
      'Taiwan Semiconductor Manufacturing Co',
      'Taiwan Semiconductor Mfg',
      'Taiwan Semiconductor Mfg Co',
      'Taiwan Semiconductor Manufacturing Company Limited',
      'Taiwan Semiconductor Manufacturing Company Ltd',
      '台積電',
      '台灣積體電路製造',
      '台灣積體電路製造股份有限公司',
    ],
    tickers: ['TSM'],
  },
  {
    id: 'nvidia',
    canonicalName: 'NVIDIA',
    aliases: ['NVIDIA Corporation', 'NVIDIA Corp', 'Nvidia'],
    tickers: ['NVDA'],
  },
  {
    id: 'amd',
    canonicalName: 'Advanced Micro Devices',
    aliases: ['AMD', 'Advanced Micro Devices Inc'],
    tickers: ['AMD'],
  },
  {
    id: 'intel',
    canonicalName: 'Intel',
    aliases: ['Intel Corporation', 'Intel Corp'],
    tickers: ['INTC'],
  },
  {
    id: 'micron',
    canonicalName: 'Micron Technology',
    aliases: ['Micron', 'Micron Technology Inc'],
    tickers: ['MU'],
  },
  {
    id: 'apple',
    canonicalName: 'Apple',
    aliases: ['Apple Inc', 'Apple Computer'],
    tickers: ['AAPL'],
  },
  {
    id: 'microsoft',
    canonicalName: 'Microsoft',
    aliases: ['Microsoft Corporation', 'Microsoft Corp'],
    tickers: ['MSFT'],
  },
  {
    id: 'amazon',
    canonicalName: 'Amazon',
    aliases: ['Amazon.com', 'Amazon.com Inc', 'AWS', 'Amazon Web Services'],
    tickers: ['AMZN'],
  },
  {
    id: 'alphabet',
    canonicalName: 'Alphabet',
    aliases: ['Google', 'Google LLC', 'Alphabet Inc'],
    tickers: ['GOOGL', 'GOOG'],
  },
  {
    id: 'meta',
    canonicalName: 'Meta',
    aliases: ['Meta Platforms', 'Facebook', 'Meta Platforms Inc'],
    tickers: ['META', 'FB'],
  },
  {
    id: 'oracle',
    canonicalName: 'Oracle',
    aliases: ['Oracle Corporation'],
    tickers: ['ORCL'],
  },
  {
    id: 'ibm',
    canonicalName: 'IBM',
    aliases: ['International Business Machines', 'International Business Machines Corp'],
    tickers: ['IBM'],
  },
  {
    id: 'dell',
    canonicalName: 'Dell Technologies',
    aliases: ['Dell', 'Dell Technologies Inc'],
    tickers: ['DELL'],
  },
  {
    id: 'hpe',
    canonicalName: 'Hewlett Packard Enterprise',
    aliases: ['HPE', 'Hewlett Packard Enterprise Co', 'Hewlett-Packard Enterprise'],
    tickers: ['HPE'],
  },
  {
    id: 'coreweave',
    canonicalName: 'CoreWeave',
    aliases: ['CoreWeave Inc', 'CoreWeave, Inc.'],
    tickers: ['CRWV'],
  },
  {
    id: 'entegris',
    canonicalName: 'Entegris',
    aliases: ['Entegris Inc', 'ENTEGRIS INC'],
    tickers: ['ENTG'],
  },
  {
    id: 'teradyne',
    canonicalName: 'Teradyne',
    aliases: ['Teradyne Inc', 'TERADYNE, INC'],
    tickers: ['TER'],
  },
  {
    id: 'super-micro',
    canonicalName: 'Super Micro Computer',
    aliases: ['Super Micro', 'Supermicro', 'Super Micro Computer Inc'],
    tickers: ['SMCI'],
  },
  {
    id: 'broadcom',
    canonicalName: 'Broadcom',
    aliases: ['Broadcom Inc', 'Broadcom Corporation'],
    tickers: ['AVGO'],
  },
  {
    id: 'qualcomm',
    canonicalName: 'Qualcomm',
    aliases: ['Qualcomm Inc', 'Qualcomm Incorporated'],
    tickers: ['QCOM'],
  },
  {
    id: 'applied-materials',
    canonicalName: 'Applied Materials',
    aliases: ['Applied Materials Inc'],
    tickers: ['AMAT'],
  },
  {
    id: 'lam-research',
    canonicalName: 'Lam Research',
    aliases: ['Lam Research Corporation'],
    tickers: ['LRCX'],
  },
  {
    id: 'kla',
    canonicalName: 'KLA',
    aliases: ['KLA Corporation', 'KLA-Tencor', 'KLA Tencor'],
    tickers: ['KLAC'],
  },
  {
    id: 'asml',
    canonicalName: 'ASML',
    aliases: ['ASML Holding', 'ASML Holding NV'],
    tickers: ['ASML'],
  },
  {
    id: 'texas-instruments',
    canonicalName: 'Texas Instruments',
    aliases: ['Texas Instruments Inc'],
    tickers: ['TXN'],
  },
  {
    id: 'analog-devices',
    canonicalName: 'Analog Devices',
    aliases: ['Analog Devices Inc'],
    tickers: ['ADI'],
  },
  {
    id: 'nxp',
    canonicalName: 'NXP Semiconductors',
    aliases: ['NXP', 'NXP Semiconductor'],
    tickers: ['NXPI'],
  },
  {
    id: 'marvell',
    canonicalName: 'Marvell Technology',
    aliases: ['Marvell', 'Marvell Technology Inc'],
    tickers: ['MRVL'],
  },
  {
    id: 'amkor',
    canonicalName: 'Amkor Technology',
    aliases: ['Amkor'],
    tickers: ['AMKR'],
  },
  {
    id: 'foxconn',
    canonicalName: 'Hon Hai Precision Industry',
    aliases: ['Hon Hai', 'Foxconn', 'Hon Hai Precision', 'Hon Hai Precision Industry Co'],
    tickers: ['2317', 'HNHPF'],
  },
  {
    id: 'samsung-electronics',
    canonicalName: 'Samsung Electronics',
    aliases: ['Samsung Electronics Co'],
    tickers: ['005930'],
  },
  {
    id: 'sk-hynix',
    canonicalName: 'SK Hynix',
    aliases: ['Hynix', 'SK hynix Inc'],
    tickers: ['000660'],
  },
  {
    id: 'globalfoundries',
    canonicalName: 'GlobalFoundries',
    aliases: ['Global Foundries', 'GlobalFoundries Inc'],
    tickers: ['GFS'],
  },
  {
    id: 'umc',
    canonicalName: 'United Microelectronics',
    aliases: ['UMC', 'United Microelectronics Corporation'],
    tickers: ['UMC'],
  },
  {
    id: 'synopsys',
    canonicalName: 'Synopsys',
    aliases: ['Synopsys Inc'],
    tickers: ['SNPS'],
  },
  {
    id: 'cadence',
    canonicalName: 'Cadence Design Systems',
    aliases: ['Cadence'],
    tickers: ['CDNS'],
  },
  {
    id: 'on-semi',
    canonicalName: 'ON Semiconductor',
    aliases: ['onsemi', 'ON Semi', 'ON Semiconductor Corporation'],
    tickers: ['ON'],
  },
]

export const OSM_REGIONS = [
  {
    id: 'hsinchu-science-park',
    south: 24.75,
    west: 120.96,
    north: 24.84,
    east: 121.08,
  },
  {
    id: 'tainan-science-park',
    south: 23.08,
    west: 120.25,
    north: 23.14,
    east: 120.33,
  },
  {
    id: 'kaohsiung-port',
    south: 22.54,
    west: 120.26,
    north: 22.64,
    east: 120.38,
  },
  {
    id: 'taoyuan-airport',
    south: 25.06,
    west: 121.2,
    north: 25.1,
    east: 121.26,
  },
  {
    id: 'chandler-az',
    south: 33.22,
    west: -111.98,
    north: 33.38,
    east: -111.8,
  },
  {
    id: 'hillsboro-or',
    south: 45.51,
    west: -122.98,
    north: 45.56,
    east: -122.88,
  },
  {
    id: 'santa-clara',
    south: 37.35,
    west: -122.03,
    north: 37.41,
    east: -121.93,
  },
  {
    id: 'phoenix-sky-harbor',
    south: 33.42,
    west: -112.03,
    north: 33.45,
    east: -111.98,
  },
]

export const SAMPOQ_CSV_URL = 'https://api.sampoq.com/datasets/supply-chain.csv'
export const OVERPASS_URL = 'https://overpass-api.de/api/interpreter'
export const OSH_API_URL = 'https://opensupplyhub.org/api/facilities/'
